name: Damage Calculation Test

on:
  push:
    branches: [ main-2023 ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js v18.15.0
      uses: actions/setup-node@v3
      with:
        node-version: '18.15.0'
    
    - run: yarn install
    - name: Install JUnit coverage reporter
      run: yarn add --dev jest-junit
    - name: Run tests with JUnit as reporter
      run: npx jest --ci --runInBand --reporters=default --reporters=jest-junit
      env:
        JEST_JUNIT_OUTPUT_DIR: "./junit/test-results.xml"
    - uses: actions/upload-artifact@v3
      with:
        path: ./junit/test-results.xml
      if: always()